name: mr_material
version: 0.1.4
description: >-
  Little material scss collection
author: Oleh Tymofieiev <oleg.timofeev20@gmail.com>
homepage: https://github.com/laboratory-rat
environment:
  sdk: '>=2.0.0 <3.0.0'